Repository PdxCodeGuild/class_opal, pull requests merged in 2022-11, with the labels that each got.

#22 lab01 complete
  code/leslie/python/lab01.py
Labels: complete

#34 lab 2 complete
  code/hayato-code/python/lab_02.py
Labels: complete

#27 draft of lab02 v1-4
  code/jim/python/lab02.py
  code/jim/python/lab02_v2.py
  code/jim/python/lab02_v3.py
  code/jim/python/lab02_v4.py
Labels: complete

#32 team diamond lab_03 ver.1
  code/mobs/diamond/lab_03.py
Labels: complete

#31 team-3 lab complete!
  code/mobs/team-3.py
Labels: complete

#33 Josh python lab02
  code/josh/python/josh_lab_2_v2.py
Labels: complete

#29 lizzie lab 02
  code/lizzie/python/lab02_ver2.py
Labels: complete

#46 lab05
  code/dj/python/lab_05.py
Labels: incomplete

#47 Josh python lab 5 version 1
  code/josh/python/josh_lab_5_v2.py
Labels: complete

#21 lizzie's python lab 1
  code/lizzie/python/lab_1.py
Labels: complete

#28 Nick lab02
  code/nick/python/lab02.py
Labels: complete

#35 lizzie lab04
  code/lizzie/lab04.py
Labels: complete

#41 Jim python lab05
  code/jim/python/lab05.py
  code/jim/python/lab05_v2.py
  code/jim/python/lab05_v3.py
Labels: complete

#42 lizzie python lab05
  code/lizzie/python/lab05.py
Labels: complete

#43 Lab 5 completed
  code/hayato-code/python/lab_05.py
Labels: complete

#36 Josh lab 4
  code/josh/josh_lab_4.py
Labels: complete

#37 jim lab04_v1-v2 submission
  code/jim/python/lab04.py
  code/jim/python/lab04_v2.py
Labels: complete

#45 Nick lab04
  code/nick/python/lab04.py
Labels: complete

#38 Hayato python lab4
  code/hayato-code/python/lab_04.py
Labels: complete

#48 jim-python-lab06
  code/jim/lab06.py
Labels: complete

#54 Leslie python lab04
  code/leslie/python/lab02.py
  code/leslie/python/lab04.py
Labels: complete

#40 lab01
  code/dj/python/lab_01.py
Labels: incomplete

#44 lab05 complete
  code/leslie/python/lab05.py
Labels: complete

#58 lab07 complete
  code/leslie/python/lab07.py
Labels: complete

#51 Lizzie lab06.py
  code/lizzie/python/lab06.py
Labels: complete

#67 Lab 7 complete
  code/hayato-code/python/lab_7.py
Labels: complete

#69 Lizzie python lab09
  code/lizzie/python/lab08_ver1.py
  code/lizzie/python/lab09_files/Gettysburg_address.txt
  code/lizzie/python/lab09_files/The_Great_Gatsby.txt
  code/lizzie/python/lab09_files/lab09.py
Labels: complete

#52 jim-python-lab08-v1v2v3
  code/jim/python/lab08.py
  code/jim/python/lab08_v2.py
  code/jim/python/lab08_v3.py
Labels: complete

#55 completed lab06
  code/nick/python/lab06.py
Labels: complete

#60 Lizzie lab07.py ver2
  code/lizzie/python/lab07.py
Labels: complete

#49 jim-python-lab07-v1v2
  code/jim/python/lab07.py
  code/jim/python/lab07_v2.py
Labels: complete

#57 lab06 completed
  code/leslie/python/lab06.py
Labels: complete

#59 Josh python lab 7 version 1
  code/josh/python/josh_lab_07.py
Labels: complete

#50 complete lab05
  code/nick/python/lab05.py
Labels: complete

#56 Josh python lab6 in progress
  code/josh/python/josh_lab_6.py
Labels: complete

#63 Nick lab07
  code/nick/python/lab07/lab07_art.py
  code/nick/python/lab07/lab07_main.py
Labels: complete

#64 jim-python-lab08-v4
  code/jim/python/lab08_v4.py
Labels: complete

#68 Josh python lab09
  code/josh/python/josh_lab_9.py
  code/josh/python/shelleysfrankenstein.txt
Labels: complete

#70 Lab 8 complete
  code/hayato-code/python/lab_8.py
Labels: complete

#72 Nick lab08
  code/nick/python/lab08.py
Labels: complete

#74 lab06-2
  code/dj/python/lab_06-2.py
Labels: complete

#81 Lab 6 v2 complete
  1 Python/examples/data/hayato-book.txt
  code/hayato-code/python/lab_6_v2.py
Labels: complete

#62 Josh python lab08 version 1 progress
  code/josh/python/josh_lab_8.py
Labels: complete

#75 Team Indecisive - Hangman lab
  code/leslie/practice/01_numbers.py
  code/leslie/practice/02_booleans.py
  code/leslie/practice/03_loops.py
  code/leslie/practice/04_strings.py
  code/leslie/practice/05_lists.py
  code/mobs/lab10/lab10_art.py
  code/mobs/lab10/lab10_main.py
Labels: complete

#76 Pumpkin spice Python Mob Lab 10
  code/mobs/ps_lab_10.py
Labels: complete

#71 lab09 complete
  code/leslie/python/christmas_carol.txt
  code/leslie/python/lab09.py
Labels: complete

#79 Lizzie lab06-2 :-)
  code/lizzie/python/lab06-2.py
Labels: complete

#78 jim-python-lab06-v2
  code/jim/python/lab06.py
  code/jim/python/lab06_v2.py
Labels: complete

#77 Josh python lab6 2
  code/josh/python/josh_lab6_2.py
Labels: complete

#82 Nick lab09
  code/nick/python/lab09/lab09.py
  code/nick/python/lab09/myth_of_sisyphus.txt
Labels: complete

#87 Nick lab06
  code/nick/python/lab06_1.py
Labels: complete

#85 lab07
  code/dj/python/lab_07.py
Labels: complete

#86 lab09
  code/dj/python/Alice-Wonder.txt
  code/dj/python/lab_09.py
Labels: complete

#84 jim-python-lab11
  code/jim/lab06.py
  code/jim/python/data/contacts.csv
  code/jim/python/data/contacts_output.csv
  code/jim/python/lab11.py
Labels: complete

#108 Jim python lab14
  code/jim/python/lab08_v4_refactor.py
  code/jim/python/lab09_refactor.py
  code/jim/python/lab12_v2_refactor.py
  code/jim/python/test_lab08_v4.py
  code/jim/python/test_lab08_v4_refactor.py
  code/jim/python/test_lab09_refactor.py
  code/jim/python/test_lab12_v2_refactor.py
Labels: complete

#103 lab13 complete
  code/leslie/python/lab13.py
Labels: complete

#98 Lizzie Python lab13
  code/lizzie/python/lab13.py
Labels: complete

#96 jim-python-lab13
  code/jim/python/lab13.py
Labels: complete

#102 Lab 13 complete
  code/hayato-code/python/lab_13.py
Labels: complete

#92 Josh Python Lab 12
  code/josh/python/josh_lab_12.py
Labels: complete

#90 lab06-2 complete
  code/leslie/python/lab06-2.py
Labels: complete

#105 lab 11 done
  code/hayato-code/python/lab_11.py
  code/hayato-code/python/my_contact.csv
Labels: complete

#88 Lizzie working lab11
  code/lizzie/python/lab11_files/contact_list.csv
  code/lizzie/python/lab11_files/lab11.py
  code/lizzie/python/lab11_files/new_contacts.csv
Labels: complete

#91 jim-python-lab12
  code/jim/python/lab12_v2.py
Labels: complete

#93 Lizzie Python lab12
  code/lizzie/python/lab12.py
Labels: incomplete

#104 Nick lab13
  code/nick/python/lab13.py
Labels: complete

#97 Nick lab11
  code/nick/python/lab11/contacts.csv
  code/nick/python/lab11/lab11.py
Labels: complete

#80 add josh python lab 11 preview to code
  code/josh/python/contacts.csv
  code/josh/python/josh_lab_11.py
Labels: complete

#109 Josh python lab13
  code/josh/python/josh_lab_13.py
Labels: incomplete

#119 Josh python lab17
  code/josh/python/josh_lab_17.py
Labels: complete

#118 Lizzie python lab17
  code/lizzie/python/lab17.py
Labels: complete

#112 Josh python lab16
  code/josh/python/josh_lab_16.py
Labels: complete

#113 jim-python-lab17_v1v2
  code/jim/python/lab17_v1.py
  code/jim/python/lab17_v2.py
Labels: complete

#117 lab16 complete -- I'm proud of this one! :)
  code/leslie/python/lab16.py
Labels: complete

#116 Lizzie python lab16
  code/lizzie/python/lab16.py
Labels: complete

#100 Nick lab04
  code/nick/python/lab04.py
Labels: complete

#111 lab12 redo complete, lab14 complete
  code/leslie/python/tests/lab08.py
  code/leslie/python/tests/lab09.py
  code/leslie/python/tests/lab12.py
  code/leslie/python/tests/test_lab14_ARI.py
  code/leslie/python/tests/test_lab14_ATM.py
  code/leslie/python/tests/test_lab14_peaks_and_valleys.py
Labels: needs review

#89 jim-python-lab11-v2
  code/jim/python/data/contacts.csv
  code/jim/python/data/contacts_output.csv
  code/jim/python/lab11.py
Labels: optional

#101 Lab 12 complete
  code/hayato-code/python/lab_12.py
Labels: incomplete

#95 lab12 complete
  code/leslie/python/lab12.py
Labels: complete

#127 lab17 complete, this one was fun
  code/nick/python/lab17.py
Labels: complete

#128 Lab 17 done
  code/hayato-code/python/lab_17.py
Labels: complete

#125 Lab 16 done
  code/hayato-code/python/lab_16.py
Labels: complete

#126 Nick lab16
  code/nick/python/lab16.py
Labels: complete
